In [68]:
import torch
checkpoint_path = "/Users/moustholmes/Projects/METAL-AI/best_models/epoch_2968.ckpt"
torch.load(checkpoint_path, map_location='cpu')

{'epoch': 2968,
 'global_step': 4456469,
 'pytorch-lightning_version': '2.3.3',
 'state_dict': OrderedDict([('model.csf_encoder.network.0.weight',
               tensor([[ 9.5847e-02, -5.7139e-02,  2.1159e-01, -1.9881e-01],
                       [-4.9229e-01, -2.5903e-01,  6.3456e-02,  4.2862e-02],
                       [-3.7332e-02, -1.6112e-01, -2.3695e-01,  1.4109e-01],
                       [ 3.8427e-01, -1.0119e-01, -3.7794e-01,  5.1001e-02],
                       [-4.3719e-05, -1.3594e-04, -6.0037e-04, -6.9436e-04],
                       [ 4.0838e-02,  5.4514e-02, -2.8760e-01,  2.6163e-01],
                       [-7.5393e-04, -1.0942e-03, -1.3627e-03, -1.3486e-03],
                       [-1.8647e-03, -1.2215e-03, -6.3518e-04, -6.3453e-04],
                       [ 4.3353e-04,  2.4351e-04, -1.4501e-03, -1.3192e-03],
                       [ 3.8829e-01, -2.9962e-01, -1.9924e-01,  2.5883e-01],
                       [ 1.7973e-06, -3.1288e-04, -1.4760e-03, -1.4390e-03],
      

In [69]:
from src.models.metalAI_module import MetalAILitModule
model = MetalAILitModule.load_from_checkpoint(checkpoint_path)
# set device to cpu
model.to('cpu')

/Users/moustholmes/miniconda3/envs/metal-ai/lib/python3.9/site-packages/lightning/pytorch/utilities/parsing.py:208: Attribute 'model' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['model'])`.
/Users/moustholmes/miniconda3/envs/metal-ai/lib/python3.9/site-packages/lightning/pytorch/utilities/parsing.py:208: Attribute 'loss_fn' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['loss_fn'])`.


MetalAILitModule(
  (model): simple_transformer_encoder_model(
    (csf_encoder): simple_CSF_encoder(
      (network): Sequential(
        (0): Linear(in_features=4, out_features=64, bias=True)
        (1): ReLU()
        (2): Linear(in_features=64, out_features=64, bias=True)
      )
    )
    (transformer_encoder): TransformerEncoder(
      (layers): ModuleList(
        (0-7): 8 x TransformerEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): NonDynamicallyQuantizableLinear(in_features=64, out_features=64, bias=True)
          )
          (linear1): Linear(in_features=64, out_features=64, bias=True)
          (dropout): Dropout(p=0.0, inplace=False)
          (linear2): Linear(in_features=64, out_features=64, bias=True)
          (norm1): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
          (norm2): LayerNorm((64,), eps=1e-05, elementwise_affine=True)
          (dropout1): Dropout(p=0.0, inplace=False)
          (dropout2): Dropout(p=0.0, inplac

In [19]:
example_input = {
    "excitations": torch.tensor(([[[5., 5.],
         [2., 5.],
         [1., 5.],
         [1., 2.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [3., 5.],
         [3., 4.],
         [2., 5.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [3., 5.],
         [3., 3.],
         [0., 5.],
         [0., 1.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([27, 14,  7]),
    "n_protons": torch.tensor([29, 17,  9]),
}

example_input2 = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [4., 5.],
         [2., 2.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[4., 5.],
         [1., 4.],
         [1., 1.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [3., 5.],
         [3., 3.],
         [0., 3.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [2., 2.],
         [5., 4.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([26, 30,  9,  5]),
    "n_protons": torch.tensor([29, 30, 10,  6]),
}

true_effect = torch.tensor([[3.9574e+00, 4.4732e+00, 2.6196e+00, 2.8538e+00, 1.0713e+00, 1.2311e-02,
         1.5218e+00],
        [2.5701e+00, 1.8061e+01, 2.4418e+00, 4.9698e+00, 1.7013e+01, 1.7055e+01,
         4.6288e-06],
        [2.5169e+00, 1.1500e+01, 1.0744e+01, 1.9679e+00, 8.8779e-01, 8.5335e+00,
         3.7076e-03]])
print("model prediction")
print(model(example_input))
print("true effect")
print(true_effect.float().tolist())
print("difference")
print(true_effect - model(example_input))

model prediction
tensor([[ 3.9621,  4.4115,  2.6016,  2.7982,  1.1327,  0.0000,  1.4966],
        [ 2.5638, 18.0370,  2.4366,  5.0462, 17.0434, 17.0972,  0.0000],
        [ 2.5332, 11.4144, 10.7573,  1.9684,  0.8789,  8.4661,  0.0000]],
       grad_fn=<SqueezeBackward1>)
true effect
[[3.95740008354187, 4.473199844360352, 2.6196000576019287, 2.853800058364868, 1.0713000297546387, 0.012311000376939774, 1.5218000411987305], [2.5701000690460205, 18.06100082397461, 2.441800117492676, 4.969799995422363, 17.01300048828125, 17.05500030517578, 4.6288000703498255e-06], [2.516900062561035, 11.5, 10.744000434875488, 1.967900037765503, 0.8877900242805481, 8.533499717712402, 0.0037076000589877367]]
difference
tensor([[-4.7443e-03,  6.1693e-02,  1.8031e-02,  5.5589e-02, -6.1394e-02,
          1.2311e-02,  2.5154e-02],
        [ 6.3171e-03,  2.3958e-02,  5.1956e-03, -7.6368e-02, -3.0418e-02,
         -4.2246e-02,  4.6288e-06],
        [-1.6344e-02,  8.5583e-02, -1.3253e-02, -4.9436e-04,  8.9344e-03,
 

In [72]:
example_input = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [2., 5.],
         [1., 5.],
         [1., 2.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [3., 5.],
         [3., 4.],
         [2., 5.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [3., 5.],
         [0., 5.],
         [3., 3.],
         [0., 1.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([27, 14,  7]),
    "n_protons": torch.tensor([29, 17,  9]),
}
example_input2 = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [4., 5.],
         [2., 2.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[4., 5.],
         [1., 4.],
         [1., 1.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [3., 5.],
         [3., 3.],
         [0., 3.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [2., 2.],
         [5., 4.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([26, 30,  9,  5]),
    "n_protons": torch.tensor([29, 30, 10,  6]),
}



model.model.train()
# model.eval()
model(example_input2)
traced_model = torch.jit.trace(model.model, example_input2)
# torch.jit.save(traced_model, "model_traced.pt")

In [36]:
# model.eval()
# scripted_model = torch.jit.script(model.model)
# torch.jit.save(scripted_model, "model_scripted.pt")


RuntimeError: 
Unsupported operation: indexing tensor with unsupported index type 'str'. Only ints, slices, lists and tensors are supported:
  File "/Users/moustholmes/Projects/METAL-AI/src/models/components/CSF_encoders.py", line 16
    def forward(self, input_dict):
        excitations = input_dict["excitations"]
                      ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        n_electrons = input_dict["n_electrons"]
        n_protons = input_dict["n_protons"]


In [74]:
import torch
loaded_model = torch.jit.load("effect_model_19_02_25.pt")
example_input2 = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [4., 5.],
         [2., 2.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[4., 5.],
         [1., 4.],
         [1., 1.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [3., 5.],
         [3., 3.],
         [0., 3.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [2., 2.],
         [5., 4.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([26, 30,  9,  5]),
    "n_protons": torch.tensor([29, 30, 10,  6]),
}

example_input = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [2., 5.],
         [1., 5.],
         [1., 2.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [4., 4.],
         [3., 5.],
         [3., 4.],
         [2., 5.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [3., 5.],
         [0., 5.],
         [3., 3.],
         [0., 1.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([27, 14,  7]),
    "n_protons": torch.tensor([29, 17,  9]),
}
loaded_model(example_input2)

CPU times: user 39.2 ms, sys: 17.5 ms, total: 56.7 ms
Wall time: 32.8 ms


tensor([[ 2.8712,  9.6136,  1.6232,  6.9724,  0.9133,  0.0452],
        [ 2.0523,  1.6758,  0.8036,  0.8194,  0.5255,  0.2203],
        [ 2.2377,  6.0404,  2.0876,  4.9966,  3.8728,  0.0000],
        [ 2.4741,  2.7234, 11.6691,  1.8075, 13.5672,  0.0000]],
       grad_fn=<SqueezeBackward1>)

In [64]:
example_input4 = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [4., 5.],
         [2., 2.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[4., 5.],
         [1., 4.],
         [1., 1.],
         [0., 4.],
         [0., 1.],
         [0., 0.]],

        [[0., 0.],
        [5., 5.],
         [5., 4.],
         [4., 4.],
         [2., 2.],
         [4., 5.],
         ]])),
    "n_electrons": torch.tensor([26, 30,    5]),
    "n_protons": torch.tensor([29, 30,   6]),
}
loaded_model(example_input4)

tensor([[ 2.8712,  9.6136,  1.6232,  6.9724,  0.9133,  0.0452],
        [ 2.0523,  1.6758,  0.8036,  0.8194,  0.5255,  0.2203],
        [ 0.0000,  2.4741, 13.5672, 11.6691,  1.8075,  2.7234]],
       grad_fn=<DifferentiableGraphBackward>)

In [40]:
example_input3 = {
    "excitations": torch.tensor(([
        [[5., 5.],
         [2., 5.],
         [1., 2.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [4., 5.],
         [3., 3.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [3., 5.],
         [3., 3.],
         [0., 5.],
         [0., 1.],
         [0., 0.]],

        [[5., 5.],
         [3., 5.],
         [3., 3.],
         [0., 5.],
         [0., 1.],
         [0., 0.]]])),
    "n_electrons": torch.tensor([27,  7,  7,  7]),
    "n_protons": torch.tensor([29,  9, 9,  9]),
}
loaded_model(example_input3)

tensor([[ 3.9702,  4.3236,  2.8093,  1.0141,  0.0000,  1.5093],
        [ 3.6509, 11.4344,  1.9881,  0.9647,  8.6526,  0.0000],
        [ 2.5343, 10.6905,  1.9299,  0.8931,  8.3529,  0.0000],
        [ 2.5343, 10.6905,  1.9299,  0.8931,  8.3529,  0.0000]],
       grad_fn=<DifferentiableGraphBackward>)

In [4]:
import torch
import os
import sys
from typing import Any, Dict

# Add the project root to the path to allow importing from src
# Adjust this to point to your project root directory
PROJECT_ROOT = "/Users/moustholmes/Projects/METAL-AI"
sys.path.append(PROJECT_ROOT)

# Function to load a model from a checkpoint
def load_model_from_checkpoint(checkpoint_path):
    """Load a model from a Lightning checkpoint file."""
    print(f"Loading checkpoint from: {checkpoint_path}")
    
    try:
        # First try the simple approach - this often works for newer Lightning versions
        checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
        
        # Check if this is a Lightning checkpoint or just a state dict
        if 'state_dict' in checkpoint:
            print("Found Lightning checkpoint with state_dict")
            state_dict = checkpoint['state_dict']
        else:
            print("Assuming checkpoint is already a state dict")
            state_dict = checkpoint
            
        print(f"Successfully loaded state dict with {len(state_dict)} parameters")
        return state_dict
        
    except Exception as e:
        print(f"Error loading checkpoint directly: {e}")
        print("Trying alternative approach...")
        
        # If there's an error, we'll try to create the model first
        # This requires importing your model classes from src
        try:
            # Import your model definition
            from src.models.components.simple_CSF_encoder import simple_CSF_encoder
            from src.models.simple_transformer_encoder_model import simple_transformer_encoder_model
            
            # Create the model with the same architecture
            csf_encoder = simple_CSF_encoder(output_size=64)
            model = simple_transformer_encoder_model(
                csf_encoder=csf_encoder,
                d_model=32,
                nhead=8,
                dim_forward=64,
                num_layers=8,
                dropout=0.0,
                output_activation=torch.nn.ReLU(),
                output_size=1
            )
            
            # Now, try to load the checkpoint into this model
            checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
            
            if 'state_dict' in checkpoint:
                model.load_state_dict(checkpoint['state_dict'])
                print("Successfully loaded checkpoint into model")
                return model.state_dict()
            else:
                model.load_state_dict(checkpoint)
                print("Successfully loaded state dict into model")
                return model.state_dict()
                
        except Exception as e2:
            print(f"Error creating model and loading checkpoint: {e2}")
            return None

# Function to export the state dict to a clean format
def export_model_weights(state_dict, output_path):
    """Export model weights to a clean PyTorch file."""
    if state_dict is None:
        print("No state dict to export")
        return False
    
    # Clean the state dict by removing any 'module.' prefixes (from DataParallel)
    clean_state_dict = {}
    for k, v in state_dict.items():
        name = k
        if name.startswith('module.'):
            name = name[7:]  # remove 'module.' prefix
        clean_state_dict[name] = v
    
    # Save the clean state dict
    try:
        torch.save(clean_state_dict, output_path)
        print(f"Successfully exported weights to: {output_path}")
        print(f"Absolute path: {os.path.abspath(output_path)}")
        return True
    except Exception as e:
        print(f"Error saving weights: {e}")
        return False

# Main function to run in your notebook
def extract_and_save_weights(checkpoint_path, output_path):
    """Load a checkpoint and save just the model weights."""
    # Load the model weights
    state_dict = load_model_from_checkpoint(checkpoint_path)
    
    # Export the weights
    if state_dict is not None:
        success = export_model_weights(state_dict, output_path)
        return success
    return False

# Example usage in your notebook:
extract_and_save_weights("/Users/moustholmes/Projects/METAL-AI/best_models/epoch_2968.ckpt", "clean_model_weights.pt")

Loading checkpoint from: /Users/moustholmes/Projects/METAL-AI/best_models/epoch_2968.ckpt
Found Lightning checkpoint with state_dict
Successfully loaded state dict with 102 parameters
Successfully exported weights to: clean_model_weights.pt
Absolute path: /Users/moustholmes/Projects/METAL-AI/src/clean_model_weights.pt


True